---
#
# Site specific values to override defaults for variables.
#
# Conventions for global environment variables:
# Use UPPERCASE underscore separated names like for shell env vars.
#
# Conventions for playbook variables:
# Use lowercase underscore separated names.
#
stack_prefix: 'sd'
#
# Versions of components of our HPC environment, which is managed using Lua+Lmod+EasyBuild.
# NOTE: when introducing a new version number here,
#       please make sure to add corresponding values in group_vars/all.yml
#
lua_version: '5.3.4'
lmod_version: '8.6.2'
easybuild_version: '4.5.1'
extra_easyconfigs_version: 1.0
extra_easyconfigs_repository: 'take-it-easyconfigs'
#
# Group folder structures to construct on shared storage systems.
#
hpc_env_prefix: '/project/xomics/Software/'
hpc_groups_prefix: '/project/xomics'
group_subfolder_structure: [
#    { group: 'umcg-atd',
#      lfs: 'tmp07',
#      mode: "{{ MODE_2770_HARD }}",
#      owner: 'umcg-atd-ateambot',
#      subfolders: ['concordance', 'generatedscripts', 'logs', 'projects', 'rawdata', 'Samplesheets', 'tmp', 'trendanalysis'],
#      machines: "{{ groups['user_interface'] }}" },
#    { group: 'umcg-gap',
#      lfs: 'tmp07',
#      mode: "{{ MODE_2770_HARD }}",
#      owner: 'umcg-gap-ateambot',
#      subfolders: ['DiagnosticOutput', 'generatedscripts', 'logs', 'projects', 'rawdata', 'Samplesheets', 'tmp'],
#      machines: "{{ groups['user_interface'] }}" },
]

# Sources, software and reference data to install/fetch.
#
public_sources: [
  'g/GCCcore/isl-0.19.tar.bz2',
  'l/libtool/libtool-2.4.6.tar.gz',
]
private_sources: []
refdata: [
  # ToDo: update for new pipelines.
  #'dbSNP',
  #'1000G',
  #'Agilent',
  #'CADD',
  #'CGD',
  #'ClinVar',
  #'Controls_Convading_XHMM',
  #'GSAarray',
  #'Ensembl',
  #'ExAC',
  #'ManVarList',
  #'gnomAD',
  #'GAVIN',
  #'GeneNetwork',
  #'HPO',
  #'UMCG',
  #'XHMM',
  #'gonl',
  #'inSilico',
  #'snpEff-4.3',
]
static_easyconfigs:
  - 'c/cluster-utils/cluster-utils-v23.04.1-GCCcore-11.3.0.eb'
  - 'd/depad-utils/depad-utils-v23.04.1.eb'
...
