---
#
# Site specific values to override defaults for variables.
#
# Conventions for global environment variables:
# Use UPPERCASE underscore separated names like for shell env vars.
#
# Conventions for playbook variables:
# Use lowercase underscore separated names.
#
stack_prefix: 'hc'
#
# Versions of components of our HPC environment, which is managed using Lua+Lmod+EasyBuild.
# NOTE: when introducing a new version number here,
#       please make sure to add corresponding values in group_vars/all.yml
#
lua_version: '5.1.4.9'
lmod_version: '7.8.8'
easybuild_version: '4.8.0'
extra_easyconfigs_version: 1.3
extra_easyconfigs_repository: 'take-it-easyconfigs'
#
# Group folder structures to construct on shared storage systems.
#
group_subfolder_structure: [
  { group: 'umcg-atd',
    lfs: 'tmp09',
    mode: "{{ MODE_2770_HARD }}",
    owner: '',
    subfolders: ['generatedscripts', 'logs', 'projects', 'rawdata', 'Samplesheets', 'tmp'],
    machines: "{{ groups['user_interface'] }}" },
  { group: 'umcg-atd',
    lfs: 'prm09',
    mode: "{{ MODE_2750_HARD }}",
    owner: 'umcg-atd-dm',
    subfolders: ['generatedscripts', 'logs', 'projects', 'rawdata', 'Samplesheets'],
    machines: "{{ groups['user_interface'] }}" },
]
#
# Sources, software and reference data to install/fetch.
#
public_sources: [
  'g/GCCcore/isl-0.19.tar.bz2',
  'l/libtool/libtool-2.4.6.tar.gz',
]
private_sources: []
refdata: [
  'dbSNP',
  '1000G',
  'NGS_DNA_Test-data/Agilent/',
  'NGS_DNA_Test-data/CADD/',
  'NGS_DNA_Test-data/gnomAD/',
  'NGS_DNA_Test-data/UMCG/',
  'CGD',
  'ClinVar',
  'Controls_Convading_XHMM',
  'GSAarray',
  'ManVarList',
  'GAVIN',
  'GeneNetwork',
  'HPO',
  'UMCG',
  'gonl',
  'inSilico',
  'snpEff-4.3',
]
easyconfigs: [
  'c/cluster-utils/cluster-utils-v23.04.1-GCCcore-11.3.0.eb',
  'd/depad-utils/depad-utils-v23.04.1.eb'
  #'n/NGS_DNA/NGS_DNA-3.5.2.eb',
]
static_easyconfigs:
  - 'c/cluster-utils/cluster-utils-v23.04.1-GCCcore-11.3.0.eb'
  - 'd/depad-utils/depad-utils-v23.04.1.eb'
...
