---
- name: Create required directories.
  file: dest="{{item}}" state='directory' mode="{{ MODE_2775_HARD }}"
  with_items:
    - "{{ easybuild_sources_dir }}/l/Lmod"
    - "{{ easybuild_sources_dir }}/l/Lua"
    - "{{ easybuild_sources_dir }}/e/EasyBuild"
    - "{{ easybuild_software_dir }}/Lua/{{ easybuild_lua_version }}"
    - "{{ easybuild_software_dir }}/EasyBuild/"
    - "{{ easybuild_modules_dir }}/all/EasyBuild"
    - "{{ easybuild_modules_dir }}/tools/EasyBuild"
    - "{{ easybuild_modules_dir }}/.lmod"
    - "{{ HPC_ENV_PREFIX }}/.tmp"

#
# Update environment.
#
- name: Create ~/.modulesrc to make sure our global modules.bashrc with Lmod and EasyBuild environment config will be sourced.
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.modulesrc"
    block: |
      export PATH={{ easybuild_software_dir }}/Lua/{{ easybuild_lua_version }}/bin:$PATH;
      export PATH={{ easybuild_software_dir }}/lmod/lmod/libexec:$PATH
      unset MODULEPATH # Make sure Lmod starts with a clean MODULEPATH
      if [ -r {{ easybuild_software_dir }}/lmod/lmod/init/bash ]; then
        source {{ easybuild_software_dir }}/lmod/lmod/init/bash
      fi
      if [ -r {{ easybuild_modules_dir }}/modules.bashrc ]; then
        source {{ easybuild_modules_dir }}/modules.bashrc
      fi
    marker: "# {mark} ANSIBLE MANAGED BLOCK - lua lmod modules in path"
    insertafter: EOF
    create: yes
- name: Create global modules.bashrc with Lmod and EasyBuild environment config.
  template: src="{{ item.src }}" dest="{{ easybuild_modules_dir }}/{{ item.dest }}" mode="{{ MODE_0664_HARD }}"
  with_items:
    - src: 'lmodrc.lua'
      dest: '.lmod/lmodrc.lua'
    - src: 'modules.bashrc'
      dest: 'modules.bashrc'
- name: Insert block into ~/.bashrc to append to make sure ~/.modulesrc will be sourced.
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      # Setup environment for Lua and Lmod.
      if [ -f "${HOME}/.modulesrc" ]; then
        . "${HOME}/.modulesrc"
      fi
    marker: "# {mark} ANSIBLE MANAGED BLOCK - lua lmod in path"
    insertafter: EOF
    create: yes

#
# Lua.
#
- name: Check if Lua is installed and if yes what version.
  #
  # Example output:
  # Lua 5.1.4.7-rtm  Copyright (C) 1994-2008 Lua.org, PUC-Rio
  #
  shell: |
         unset MODULEPATH
         source ~/.modulesrc >/dev/null 2>&1
         lua -v  2>&1 | grep -i Lua | sed 's|^.*Lua \([0-9\.]*\).*$|\1|'
  args:
    executable: /bin/bash
    warn: no
  environment:
    SOURCE_HPC_ENV: "True"   # Required to source our modules.bashrc in non-interactive shells.
  changed_when: false
  failed_when: false
  check_mode: no
  register: lua_installed_version 
- name: Report Lua status.
  debug:
    #msg: 'Will install Lua from source as it is either missing or present in a different version. (Detected {{ lua_installed_version.stderr | regex_replace("^.*Lua ([0-9\.]+).*$", "\\1") }} and need {{ easybuild_lua_version }}.)'
    msg: 'Will install Lua from source as it is either missing or present in a different version. (Detected {{ lua_installed_version.stdout }} and need {{ easybuild_lua_version }}.)'
  when:         'lua_installed_version|failed or (lua_installed_version.stdout | version_compare(easybuild_lua_version, operator="!="))'
  changed_when: 'lua_installed_version|failed or (lua_installed_version.stdout | version_compare(easybuild_lua_version, operator="!="))'
  notify: 'Install_Lua_Lmod_EasyBuild_trio'

#
# Lmod.
#
- name: Check if Lmod is installed and if yes what version.
  #
  # Example output:
  # Modules based on Lua: Version 6.5.8  2016-09-03 13:41 -05:00 (CDT)
  #    by Robert McLay mclay@tacc.utexas.edu
  #
  shell: |
         unset MODULEPATH
         source ~/.modulesrc >/dev/null 2>&1
         lmod -v 2>&1 | sed '/^$/d' | sed 's|^.*Version \([0-9\.]*\).*$|\1|' | head -1
  args:
    executable: /bin/bash
    warn: no
  environment:
    SOURCE_HPC_ENV: "True"   # Required to source our modules.bashrc in non-interactive shells.
  changed_when: false
  failed_when: false
  check_mode: no
  register: lmod_installed_version
- name: Report Lmod status.
  debug:
    msg: 'Will install Lmod from source as it is either missing or present in a different version. (Detected {{ lmod_installed_version.stdout }} and need {{ easybuild_lmod_version }}.)'
  when:         'lmod_installed_version|failed or (lmod_installed_version.stdout | version_compare(easybuild_lmod_version, operator="!="))'
  changed_when: 'lmod_installed_version|failed or (lmod_installed_version.stdout | version_compare(easybuild_lmod_version, operator="!="))'
  notify: 'Install_Lua_Lmod_EasyBuild_trio'

#
# EasyBuild.
#
- name: Check if EasyBuild is installed and if yes what version.
  shell: |
         source ~/.modulesrc >/dev/null 2>&1
         module load EasyBuild/{{ easybuild_eb_version }}
         eb --version 2>&1 | sed 's|^This is EasyBuild \([0-9\.]*\).*$|\1|'
  args:
    executable: /bin/bash
    warn: no
  environment:
    SOURCE_HPC_ENV: "True"   # Required to source our modules.bashrc in non-interactive shells.
  changed_when: false
  failed_when: false
  check_mode: no
  register: eb_installed_version
#- name: DEBUG EasyBuild version number.
#  debug:
#    msg: 'Detected {{ eb_installed_version.stdout | version_compare(easybuild_eb_version, operator="!=") }}.'
#- debug: var=eb_installed_version
- name: Report EasyBuild status.
  debug:
    msg: 'Will bootstrap the latest EasyBuild version from source as it is either missing or present in a different version. (Detected {{ eb_installed_version.stdout }} and need {{ easybuild_eb_version }}.)'
  when:         'eb_installed_version|failed or (eb_installed_version.stdout | version_compare(easybuild_eb_version, operator="!="))'
  changed_when: 'eb_installed_version|failed or (eb_installed_version.stdout | version_compare(easybuild_eb_version, operator="!="))'
  notify: 'Install_Lua_Lmod_EasyBuild_trio'

- meta: flush_handlers
...
